### ISSUE TITLE
Blackscreen when using DSI screen

### ISSUE THREAD

**Issue by nimans4** [fayaaz/mixxx-pi-gen#12]
I am using a RPi 4 with the 7'' RPi Touchscreen.
I flashed the SD and booted the RPi.
After the colored testdisplay, the "resizing the storage"- image and the text(?) with all the green [OK]s, I'm getting a black screen.
I've waited for at least 15 min but nothing happened.
Maybe it's due to the screensize? No skin in mixxx can be downscaled to 800x480, so I needed to change the skin.xml in my old RPi setup with the normal Desktop .img .

Any clues?

**Comment by fayaaz** [comment]
Hi @nimans4 did you use HDMI1 or HDMI2 for the screen? I seem to have a lot more luck with HDMI2 (the port furthest away from the power). This should contain a 800x480 skin but looks like your screen isn't setting the right resolution on boot.

If HDMI2 doesn't work is there a way you can force the resolution in /boot/config.txt?

**Comment by nimans4** [comment]
My Screen ist connected to the Raspberry Pi MIPI DSI, not to micro-HDMI.
Also I don't have any access to the terminal or any kind of method to use the keyboard.

**Comment by fayaaz** [comment]
@nimans4 could you give me a link to the model and check it out - without one there's not much I can do but suggest fixes. I would also suggest plugging the raspberry pi into ethernet if you can to SSH in to do further debugging.

**Comment by nimans4** [comment]
@fayaaz 

https://www.raspberrypi.org/products/raspberry-pi-touch-display/
That's my display, I just connected two jumper cables for power, it worked fine without the other two on raspbian os.

I don't know yet what ssh is, but I will check it out !

**Comment by fayaaz** [comment]
Just as a point of comparison does your screen work with the beta 64 bit image [here](https://www.raspberrypi.org/forums/viewtopic.php?t=275370)

**Comment by nimans4** [comment]
@fayaaz  
Will try it out tomorrow !
Keep you updated
Thank you for your help

**Comment by nimans4** [comment]
@fayaaz 
Screen works fine with the 64 bit beta image!

**Comment by fayaaz** [comment]
Hi @nimans4 sorry for the delay - I had a look at the differences between the beta 64 bit image and mine: https://github.com/RPi-Distro/pi-gen/compare/arm64...fayaaz:master

The only thing I can see is this: https://github.com/RPi-Distro/pi-gen/compare/arm64...fayaaz:master#diff-7871b17682144c24ba1016577735ab32c2e46049d455e28b94cd2422d412b66dR59

Therefore I would suggest SSHing into the Pi and in /boot/config.txt changing:
```dtoverlay=vc4-kms-v3d```
to
```dtoverlay=vc4-fkms-v3d```

and rebooting. Let me know if that helps. This is unfortunately only a guess.

**Comment by nimans4** [comment]
yeeees, it works! THANK YOU for that! Just need to tweak the skin a little bit, but for now its running smoothly!

**Comment by fayaaz** [comment]
Thanks for reporting back, I will fix it in the image. However the current build is broken with Mixxx on the 2.3 branch since the keyfinder update so I will need to investigate that first.

**Comment by fayaaz** [comment]
Using fkms causes my X server to break :(

```
/usr/lib/xorg/Xorg: symbol lookup error: /usr/lib/xorg/modules/drivers/fbturbo_drv.so: undefined symbol: shadowUpdatePackedWeak
```

Might be more info here - 

https://forums.balena.io/t/x11-with-multiple-displays/58415/14

I wonder if this is helpful:
https://git.busybox.net/buildroot/commit/?id=25e5c401fa3b1082653e0313b9f7bbeac1a06533

**Comment by fayaaz** [comment]
@nimans4 I think I have fixed the issue with the new image. Let me know if you get a chance to test it and I will close this issue if it's working.

**Comment by nimans4** [comment]
Will try it out as soon as I got time!
