### ISSUE TITLE
Can't find a way to turn on absolute vinyl control mode on a small screen.

### ISSUE THREAD

**Issue by iandoesallthethings** [fayaaz/mixxx-pi-gen#23]
I'm using one of the 7" touch screens. It works great with the minimal skin, but vinyl control is stuck in relative mode. There are some buttons cut off at the bottom, but according to your screenshots, none of them are the rel/abs buttons. 

![PXL_20210528_020308420](https://user-images.githubusercontent.com/15148313/119919048-99d65880-bf37-11eb-8766-9db15fba683c.jpg)

The menu on the right won't seem to open, either, which I thought might be hiding them.

P.S. Performance is spectacular, and the image worked 1st try! Thanks for all the hard work! :D

**Comment by fayaaz** [comment]
Hello, the skin as created by @dennisdebel here: https://github.com/dennisdebel/pi_dj - this repo builds it from his github. Unfortunately I can't be much help otherwise.

**Comment by iandoesallthethings** [comment]
That's super helpful, thank you!
