### ISSUE TITLE
Performance on Raspi 4

### ISSUE THREAD

**Issue by MaxHausmann** [fayaaz/mixxx-pi-gen#24]
Do you have any performance specs for this build? 
As you know, Raspi 4 boards have different RAM-sizes, so I want to
buy a suitable board.

**Comment by slashtechno** [comment]
@MaxHausmann My experience when using Mixxx on my Raspberry Pi 4 (4 GB RAM) is it works nicely, however, recording quality is quite bad.

You could also install [Raspberry Pi Desktop](https://www.raspberrypi.org/software/raspberry-pi-desktop/) in a VM on your computer and try different RAM amounts.

**Comment by fayaaz** [comment]
For 2 decks it seems like the 2GB version is acceptable. YMMV depending on acceptable latencies and sampling rates of files you're using.

For recording @slashtechno the limiting factor would possibly be the sd card storage - not sure of a way around this. I actually use another raspberry pi mounted through samba for my library.
