### ISSUE TITLE
realtime kernel

### ISSUE THREAD

**Issue by K3nn3th2** [fayaaz/mixxx-pi-gen#28]
hey guys,

does the generated image contain a PREEMPT_RT_FULL patched kernel? 
what kernel version does it contain?

thanks!

**Comment by fayaaz** [comment]
Nope, it has the mainline kernel with `irqthreads` command line flag enabled as that is what is recommended by Mixxx.

**Comment by K3nn3th2** [comment]
thanks for the reply! can you point me to the recommendation?
i personally have always had the best perfomance and lowest latencies with mixxx/xwax using an rt kernel, hence the question..

**Comment by fayaaz** [comment]
https://github.com/mixxxdj/mixxx/wiki/Adjusting-Audio-Latency

after much discussion with the devs on zulip as well, it was declared sufficient to run the mainline kernel with `threadirqs` for Mixxx to be able to take advantage of realtime scheduling. It may be worth asking the question again in case anything has changed.
