### ISSUE TITLE
How to add a controller definition?

### ISSUE THREAD

**Issue by dwaynarang** [fayaaz/mixxx-pi-gen#32]
This is probably easy, but how do I add a controller definition to Mixxx? I'm trying to add the DDJ-SB3 definition that's floating around. It says I can either run a script or manually copy the files. I was able to copy the Pioneer-DDJ-SB3-scripts.js
Pioneer-DDJ-SB3.midi.xml files to my /code/res/controllers folder but they don't appear in the dropdown menu in Mixxx.

**Comment by fayaaz** [comment]
You will want to copy them to `/home/pi/.mixxx/controllers` the `/code/` folder is not used after the initial build, but I can understand your confusion.
