### ISSUE TITLE
No Interface

### ISSUE THREAD

**Issue by Patman7331** [fayaaz/mixxx-pi-gen#39]
I just downloaded the latest version and installed it in my Rpi4 8gb and all i get seems to be an almost black version 

on the left corner is a litte blue sign that reads "1:Mixxx" and on the right corner i see "No IPv6 / 22.5gb / W: down / E: down / no battery / 0,01/ and the current date

waited several minutes and nothing happened, cant click anything, can open console but didn't found a helpful command

keep up the good work

**Comment by fayaaz** [comment]
@Patman7331 please check the GPU memory split you have with `sudo raspi-config` and give at least 128MB to the GPU. Let me know if this fixes it for you.
