### ISSUE TITLE
Screen cut in half Screen 7Inch

### ISSUE THREAD

**Issue by MathisZerbib** [fayaaz/mixxx-pi-gen#50]
Hello, I have a rapsberry bi 4b+ 8gb with an official 7inch screen

I can't load a theme minimal resolution that I have downloaded open source.

Where I can find the .mixxx/theme folder ?

**Comment by fayaaz** [comment]
@MathisZerbib, the skins folder is here on disk: `/usr/share/mixxx/skins/`

**Comment by MathisZerbib** [comment]
Thanks for your response ! I think I was wrong to write ./theme instead of ./skins ! I will keep you updated about my project, this raspberry and this project have done so much so far !

Info : 
-  Rapsberry bi 4b+ 8gb
-  7inch Touch Screen
-  S2Mk3 Native Instruments
- Power bank 6000mAh

**Comment by MathisZerbib** [comment]
I didn't managed to get this work on raspberry, 

Bugs in current themes can't click with my fingers on the screen, also this is not fully responsive, please make it ❤️❤️

**Comment by fayaaz** [comment]
This will be down to the maintainers of mixxx and if they support touch on the interface. Sorry I cannot be more help.
