### ISSUE TITLE
Date is not updating

### ISSUE THREAD

**Issue by percolator25** [fayaaz/mixxx-pi-gen#55]
Hello,

thank you for this great distro. I am using v2 on a Raspi 4B since a while now and had no issues. But now I created a new SD card with the newest release  v3 and for some reason the update of the date is not working. I tried to sync/activate with datetimectl, but it tells me there is no ntpd and it is not syncing. I let the Pi run for several hours, network connection is fine, but still no updates, it is always June for the Pi. Am I missing something here?

**Comment by fayaaz** [comment]
Thanks for reporting this!
You will need to install the systemd daemon: `sudo apt-get install systemd-timesyncd`
I will make sure to include it in the future release.

**Comment by percolator25** [comment]
Thank you very much. I am currently using a default Raspberry OS, but will test the next release.
