### ISSUE TITLE
Can't figure out how to mount any USB Drives/SSDs

### ISSUE THREAD

**Issue by FreakyBro** [fayaaz/mixxx-pi-gen#57]
Hi, this does not work with any of my USB sticks on my Raspberry Pi 4, they are never detected... what am I doing wrong?

**Comment by fayaaz** [comment]
This was reported here: https://github.com/fayaaz/mixxx-pi-gen/issues/52

Not sure if this is a problem, the OP never replied. Do they not show up under removable media in the left hand pane? If not could you open a shell with Win+Enter and check if there's a new folder for your driver under /media/pi or /run/media/.

devmon (not quite sure if it's udevil  or udisks2) should run when i3 starts. It's puzzling that multiple people have reported this but I cannot recreate. I'll test it again when I do the next release.

**Comment by fayaaz** [comment]
Confirmed working mounting ext4 usb and it showing up under removable devices.

Unconfirmed - NTFS drive
