### ISSUE TITLE
i3 goes black intermittently

### ISSUE THREAD

**Issue by fayaaz** [fayaaz/mixxx-pi-gen#6]
Happens when playing with FX or opening up a new tiled window.

**Comment by jstavats** [comment]
Hi, I’ve been fighting with another video issue on this. For whatever reason i3 is coming up with an unsupported video resolution on my TV. I see video from my pi4 until then, but no matter which mode i try to set (using xrandx in the i3 config file) it just says no input. The same TV has never had any issue with stock rasbian. I can get video on some other monitors with this, but they do have the black flicker periodically. Also some of those monitors periodically show corrupt mouse pointers or screen data (lots of randomly coloured  pixels).

**Comment by fayaaz** [comment]
@jstavats I had this problem and switched to HDMI2 and it seemed to work - not sure what the problem is with HDMI1. Will investigate.

**Comment by fayaaz** [comment]
Hi @jstavats I have just published a new version. It seems to work on HDMI1 although I get an under-scan which I don't with HDMI2. I also have not seen the black flicker with this version. Let me know if you manage to test it.

**Comment by fayaaz** [comment]
Closing issue as HDMI1 and HDMI2 should be working now.
