### ISSUE TITLE
Use mixxx 2.4.0 beta release

### ISSUE THREAD

**Issue by irijff** [fayaaz/mixxx-pi-gen#65]
Mixxx 2.4 is now in beta (available from the [mixxxbetas PPA](https://launchpad.net/~mixxx/+archive/ubuntu/mixxxbetas), but the generated image still comes with the last alpha version.

**Comment by fayaaz** [comment]
Should be updated in https://github.com/fayaaz/mixxx-pi-gen/releases/tag/v0.8.0
