### ISSUE TITLE
USB not recognized

### ISSUE THREAD

**Issue by MeesJense** [fayaaz/mixxx-pi-gen#66]
Hi, 
I did this installation and it all seems to work, but when I plug in my USB, does not pop up in the library menu. When I plug the USB in my laptop it works fine.
Any idea why this is the case? And are there other ways to install music on the Pi?

**Comment by fayaaz** [comment]
@MeesJense do you still have this problem? There have been a few reports of this but have not been able to recreate it. On my most recent image, I can plug in a USB and it appears under /media/<username>/<disk name> - Rekordbox'd USBs should also appear, but cannot confirm that right now.
