### ISSUE TITLE
Mixxx 2.4 Released and OnBoard virtual keyboard

### ISSUE THREAD

**Issue by Sheyk90** [fayaaz/mixxx-pi-gen#76]
Final version Mixxx 2.4 was released. Could you update it?

Another interesting aspect, adding a virtual keyboard (Onboard) so that when you click on the search tab in the library you can write, since it is missed.

Thanks

**Comment by fayaaz** [comment]
Hey @Sheyk90  you can always help me test it by getting the latest image from the actions and seeing if it works ok - it should contain Mixxx 2.4.

https://github.com/fayaaz/mixxx-pi-gen/actions/runs/7998081913

About the keyboard - here's a discussion thread about it. 
https://github.com/fayaaz/mixxx-pi-gen/discussions/75
I'm thinking of adding the script to the image - the keyboard is already installed.
