### ISSUE TITLE
Saving settings

### ISSUE THREAD

**Issue by 5p4m3r** [fayaaz/mixxx-pi-gen#9]
Mixxx does not save the settings on proper quit or shut down.
The audio output routing is saved but not the controller mapping/selection, interface skin and others.
But nevertheless nice build, it's running smooth on the RPI 4 4gb.

**Comment by fayaaz** [comment]
Hi, for some reason this can happen on an illegal shutdown of Mixxx. Have a look at the mixxx logs and see if there's references to a sandbox config file. Delete that and restart everything. Make sure you exit Mixxx before shutting down the Raspberry Pi this time.

**Comment by 5p4m3r** [comment]
Hi,
I had the problem with even with a proper shut down of mixxx, it did not create a proper sandbox or a mixxx  config file instead sandbox.cfg.tmp and mixxx.cfg.tmp files were created.
I just copied the mixxx.cfg.tmp and renamed it to mixxx,cfg rebooted, adjusted my settings and after proper shutdown all was saved.

**Comment by fayaaz** [comment]
Looks like this was fixed in Mixxx recently - I will release a new version with the updated Mixxx soon in that case.

ref: https://mixxx.zulipchat.com/#narrow/stream/109695-_support/topic/Mixxx.20settings.20not.20saved

**Comment by fayaaz** [comment]
New version released - it should fix this. Closing this issue unless the problem persists.
