### ISSUE TITLE
Expand file system on first boot

### ISSUE THREAD

**Issue by GorgiAstro** [fayaaz/mixxx-pi-gen#92]
Hi, first thanks a lot for this amazing RPi image!

I noticed that the SD's file system does not automatically expand on first boot, and therefore there is barely any space available on the partition.

Is it possible to add a script which expands the file system on first boot, like this one? https://forums.raspberrypi.com/viewtopic.php?t=353185

Alternatively, we could tell users in the documentation to use [sdm](https://github.com/gitbls/sdm) with the `--expand-root` option to write the `.img` onto the SD card:

**Comment by fayaaz** [comment]
Weird, it should do this already. I'll check next time I update the image.

**Comment by fayaaz** [comment]
Closed as not reproducible
